### ISSUE TITLE
Batch Requests present a bug

### ISSUE THREAD

**Issue by benrfairless** [openaustralia/righttoknow#515]
I get a bug when attempting to make batch requests in Production:

Sorry, there was a problem processing this page
You have found a bug. Please contact us to tell us about the problem

**Comment by benrfairless** [comment]
I can't test this in staging as batch processing isn't enabled in staging. Trying to test this in my Vagrant development environment now

**Comment by benrfairless** [comment]
Found this when I did a batch request in Development:

```
NoMethodError in RequestController#new_batch
undefined method `jurisdiction' for nil:NilClass
```

Full Trace:

```
lib/themes/righttoknow/lib/model_patches.rb:58:in `australian_law_used'
lib/themes/righttoknow/lib/model_patches.rb:86:in `law_used_short'
app/views/request/new.html.erb:38:in `_app_views_request_new_html_erb__886685361_70280524180140'
actionpack (3.2.21) lib/action_view/template.rb:145:in `send'
actionpack (3.2.21) lib/action_view/template.rb:145:in `render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `render'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
app/controllers/request_controller.rb:1081:in `render_new_compose'
app/controllers/request_controller.rb:214:in `new_batch'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `process_action'
activesupport (3.2.21) lib/active_support/callbacks.rb:569:in `_run__1189048994__process_action__1699291458__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `_conditional_callback_around_775'
app/controllers/application_controller.rb:111:in `record_memory'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_775'
activesupport (3.2.21) lib/active_support/callbacks.rb:557:in `_run__1189048994__process_action__1699291458__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:35:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2114057945__call__4__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `send'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `send'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call_without_quiet_assets'
activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call_without_quiet_assets'
quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.5.1) lib/thin/connection.rb:81:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:79:in `catch'
thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
thin (1.5.1) lib/thin/connection.rb:54:in `process'
thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
thin (1.5.1) lib/thin/server.rb:159:in `start'
rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.5) lib/rack/server.rb:268:in `start'
railties (3.2.21) lib/rails/commands/server.rb:70:in `start'
railties (3.2.21) lib/rails/commands.rb:55
railties (3.2.21) lib/rails/commands.rb:50:in `tap'
railties (3.2.21) lib/rails/commands.rb:50
script/rails:6:in `require'
script/rails:6
```

**Comment by henare** [comment]
Thanks for finding this Ben. My mistake - I should have tested batch requests properly.

> I can't test this in staging as batch processing isn't enabled in staging.

I've enabled this in staging because it should be configured as similar to production as possible.
