### ISSUE TITLE
alert-not-clarified-request cronjob not working

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#574]
Looks like it's been broken for a while:

```
/srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands/runner.rb:54:in `eval': internal error, no last response while making alert not clarified reminder, request id 1377 (RuntimeError)
        from /srv/www/www.righttoknow.org.au/releases/20160725133348/app/mailers/request_mailer.rb:376:in `each'
        from /srv/www/www.righttoknow.org.au/releases/20160725133348/app/mailers/request_mailer.rb:376:in `alert_not_clarified_request'
        from (eval):1:in `<top (required)>'
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands/runner.rb:54:in `eval'
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands/runner.rb:54:in `<top (required)>'
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands.rb:64:in `require'
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.21/lib/rails/commands.rb:64:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by henare** [comment]
It was because this request had a described state of "waiting clarification" yet it had no incoming messages. We must have accidentally set that state when we hid this request for personal information.

I corrected the described state to "waiting response" and now the cronjob runs fine.
