### ISSUE TITLE
Can't download a particular PDF attachment on one request

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#576]
Trying to download this throws an exception after a very long wait: https://www.righttoknow.org.au/request/1190/response/4122/attach/4/FOI%20request%20Operation%20Fortitude%20as%20released.pdf

```
A NoMemoryError occurred in request#get_attachment:

  failed to allocate memory
  lib/alaveteli_external_command.rb:50:in `inspect'


-------------------------------
Request:
-------------------------------

  * URL       : https://www.righttoknow.org.au/request/1190/response/4122/attach/4/FOI%20request%20Operation%20Fortitude%20as%20released.pdf
  * IP address: 127.0.0.1
  * Parameters: {"controller"=>"request", "action"=>"get_attachment", "id"=>"1190", "incoming_message_id"=>"4122", "part"=>"4", "file_name"=>"FOI request Operation Fortitude as released.pdf"}
  * Rails root: /srv/www/www.righttoknow.org.au/releases/20160725133348
  * Timestamp : 2016-07-28 07:28:19 +1000
```

**Comment by henare** [comment]
I've asked the list https://groups.google.com/forum/#!topic/alaveteli-dev/UvKPMALqteM

**Comment by henare** [comment]
And sent a follow up.

**Comment by henare** [comment]
@lizconlan helpfully suggested:

> The quick fix is to disable ghostscript in your general.yml file (by setting USE_GHOSTSCRIPT_COMPRESSION to false) which is how we've got WDTK set up.

and it's worked :tada: Thanks Liz!

**Comment by henare** [comment]
Similar problem happening again with this: https://www.righttoknow.org.au/request/772/response/2924/attach/2/Documents%20for%20release%20Part%202.pdf

```
A NoMemoryError occurred in request#get_attachment:

  failed to allocate memory
  lib/alaveteli_text_masker.rb:128:in `gsub!'
```

**Comment by henare** [comment]
For whatever reason that now seems to be working.
