### ISSUE TITLE
foi-alert-tracks crashing

### ISSUE THREAD

**Issue by henare** [openaustralia/righttoknow#598]
We recently upgraded to 0.25.0.1, was this the problem?

Weirdly it didn't start happening until 21:05 last night, I was doing something on the server then but I didn't think would be related.

```
Daemon starting at 2016-08-16 09:55:01 +1000                                                                                                                            
/srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands/runner.rb:54:in `eval': Validation failed: User|About me Please keep it shorter than 500 characters (ActiveRecord::RecordInvalid)                                                                                                            
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/attribute_methods/dirty.rb:33:in `save!'             
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:264:in `block in save!'              
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'                                                                                                                                                          
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'                                                                                                                                                     
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:208:in `transaction'                 
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'                                                                                                                                                                   
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:264:in `save!'                       
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'                                                                                                                                                           
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent.rb:571:in `with_database_metric_name'            
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.16.0.318/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'                                                                                                                                                                    
        from /srv/www/www.righttoknow.org.au/releases/20160815071131/app/mailers/track_mailer.rb:119:in `block in alert_tracks'                                         
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/batches.rb:21:in `block (2 levels) in find_each'                                                                                                                                                                    
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/batches.rb:21:in `each'                     
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/batches.rb:21:in `block in find_each'       
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/batches.rb:72:in `find_in_batches'          
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/relation/batches.rb:20:in `find_each'                
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.22.2/lib/active_record/querying.rb:8:in `find_each'                         
        from /srv/www/www.righttoknow.org.au/releases/20160815071131/app/mailers/track_mailer.rb:44:in `alert_tracks'                                                   
        from /srv/www/www.righttoknow.org.au/releases/20160815071131/app/mailers/track_mailer.rb:129:in `alert_tracks_loop'                                             
        from (eval):1:in `<top (required)>'                                                                                                                             
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands/runner.rb:54:in `eval'                                  
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands/runner.rb:54:in `<top (required)>'                      
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands.rb:64:in `require'                                      
        from /srv/www/www.righttoknow.org.au/shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands.rb:64:in `<top (required)>'                             
        from script/rails:6:in `require'                                                                                                                                
        from script/rails:6:in `<main>'                                                                                                                                 
```

**Comment by henare** [comment]
Unsurprisingly it's because one user's about_me is longer than 500 characters. How that happened I've got no idea - AFAIK the validations have been on for ages.

> Weirdly it didn't start happening until 21:05 last night, I was doing something on the server then but I didn't think would be related.

That's because it's when that user's email was due to go out.

I've truncated the about me for that user, notified them, and it seems to be working again.
